/* Table : ASSISTER                                             */
CREATE TABLE ASSISTER (
   NUMERO INTEGER NOT NULL,
   IDCONF INTEGER NOT NULL,
   CONSTRAINT PK_ASSISTER PRIMARY KEY (NUMERO, IDCONF)
);

/* ASSISTER_FK */
CREATE INDEX ASSISTER_FK ON ASSISTER (
   NUMERO ASC
);

/* Index : ASSISTER2_FK                                         */
CREATE INDEX ASSISTER2_FK ON ASSISTER (
   IDCONF ASC
);

/* Table : BULLETIN                                             */
CREATE TABLE BULLETIN (
   MONTANTINDEMNITE INTEGER NOT NULL,
   DATEBUL DATE NOT NULL,
   IDFORM INTEGER NOT NULL,
   CONSTRAINT PK_BULLETIN PRIMARY KEY (DATEBUL)
);

/* Index : SUBVENTIONNER_FK                                     */
CREATE INDEX SUBVENTIONNER_FK ON BULLETIN (
   IDFORM ASC
);

/* Table : CONFERENCE                                           */
CREATE TABLE CONFERENCE (
   DOMAINECONF VARCHAR2(1024) NOT NULL,
   DATECONF DATE NOT NULL,
   IDCONF INTEGER NOT NULL,
   IDFORM INTEGER NOT NULL,
   CONSTRAINT PK_CONFERENCE PRIMARY KEY (IDCONF)
);

/* Index : ANIMER_FK                                            */
CREATE INDEX ANIMER_FK ON CONFERENCE (
   IDFORM ASC
);

/* Table : COURS                                                */

CREATE TABLE COURS (
   LIEUCOURS VARCHAR2(1024) NOT NULL,
   INTITULECOURS VARCHAR2(1024) NOT NULL,
   CODECOURS INTEGER NOT NULL,
   ANNEECOURS INTEGER NOT NULL,
   IDFORM INTEGER NOT NULL,
   CONSTRAINT PK_COURS PRIMARY KEY (ANNEECOURS, CODECOURS)
);

/* Index : ENSEIGNER_FK                                         */

CREATE INDEX ENSEIGNER_FK ON COURS (
   IDFORM ASC
);

/* Table : ENGAGER                                              */

CREATE TABLE ENGAGER (
   NUMERO INTEGER NOT NULL,
   ANNEECOURS INTEGER NOT NULL,
   CODECOURS INTEGER NOT NULL,
   MONTANT FLOAT(8) NOT NULL,
   SOLDE FLOAT(8) NOT NULL,
   CONSTRAINT PK_ENGAGER PRIMARY KEY (NUMERO, ANNEECOURS, CODECOURS)
);

/* Index : ENGAGER_FK                                           */

CREATE INDEX ENGAGER_FK ON ENGAGER (
   NUMERO ASC
);

/* Index : ENGAGER2_FK                                          */

CREATE INDEX ENGAGER2_FK ON ENGAGER (
   ANNEECOURS ASC,
   CODECOURS ASC
);

/* Table : FINANCER                                             */

CREATE TABLE FINANCER (
   IDCONF INTEGER NOT NULL,
   DATEFIN DATE NOT NULL,
   FORFAITCONF FLOAT NOT NULL,
   CONSTRAINT PK_FINANCER PRIMARY KEY (IDCONF, DATEFIN)
);

/* Index : FINANCER_FK                                          */

CREATE INDEX FINANCER_FK ON FINANCER (
   IDCONF ASC
);

/* Index : FINANCER2_FK                                         */

CREATE INDEX FINANCER2_FK ON FINANCER (
  DATEFIN ASC
);

/* Table : FORMATEUR                                            */

CREATE TABLE FORMATEUR (
   PRENOMFORM VARCHAR2(1024) NOT NULL,
   TITREFORM VARCHAR2(1024) NOT NULL,
   IDFORM INTEGER NOT NULL,
   CONSTRAINT PK_FORMATEUR PRIMARY KEY (IDFORM)
);

/* Table : PARTICIPANT                                          */

CREATE TABLE PARTICIPANT (
   NOMPATIENT VARCHAR2(1024) NOT NULL,
   ADRESSEPAT VARCHAR2(1024) NOT NULL,
   CODEPOSTALPAT INTEGER NOT NULL,
   VILLEPAT VARCHAR2(1024) NOT NULL,
   DDNPAT DATE NOT NULL,
   PROFPAT VARCHAR2(1024) NOT NULL,
   NUMERO INTEGER NOT NULL,
   CONSTRAINT PK_PARTICIPANT PRIMARY KEY (NUMERO)
);

/* Table : PARTICIPER                                           */

CREATE TABLE PARTICIPER (
  NUMEROPART INTEGER NOT NULL,
  IDSQ INTEGER NOT NULL,
  CONSTRAINT PK_PARTICIPER PRIMARY KEY (NUMEROPART, IDSQ)
);


/* Index : PARTICIPER_FK                                        */

CREATE INDEX PARTICIPER_FK ON PARTICIPER (
   NUMEROPART ASC
);

/* Index : PARTICIPER2_FK                                       */

CREATE INDEX PARTICIPER2_FK ON PARTICIPER (
   IDSQ ASC
);

/* Table : PAYER                                                */

CREATE TABLE PAYER (
   IDSQ INTEGER NOT NULL,
   DATEPAY DATE NOT NULL,
   FORFAITSQ FLOAT NOT NULL,
   CONSTRAINT PK_PAYER PRIMARY KEY (IDSQ, DATEPAY)
);

/* Index : PAYER_FK                                             */

CREATE INDEX PAYER_FK ON PAYER (
   IDSQ ASC
);

/* Index : PAYER2_FK                                            */

CREATE INDEX PAYER2_FK ON PAYER (
   DATEPAY ASC
);

/* Table : SEQUENCE                                             */
CREATE TABLE SEQUENCE (
   DATESQ DATE NOT NULL,
   DUREESQ INTEGER NOT NULL,
   IDSQ INTEGER NOT NULL,
   ANNEECOURS INTEGER NOT NULL,
   CODECOURS INTEGER NOT NULL,
   ETATSQ VARCHAR2(1024) NOT NULL,
   CONSTRAINT PK_SEQUENCE PRIMARY KEY (IDSQ)
);

/* Index : CONTENIR_FK                                          */
CREATE INDEX CONTENIR_FK ON SEQUENCE (
   ANNEECOURS ASC,
   CODECOURS ASC
);

/* Table : COMPETENCE                                           */

CREATE TABLE COMPETENCE (
  IDCOMPT INTEGER NOT NULL,
  INTITULECOMPT VARCHAR(1024) NOT NULL,
  CONSTRAINT PK_COMPETENCE PRIMARY KEY (IDCOMPT)
);


/* Table : ETREDOTE                                              */
CREATE TABLE ETREDOTE (
  IDFORM INT NOT NULL,
  IDCOMPT INTEGER NOT NULL,
  CONSTRAINT PK_ETREDOTE PRIMARY KEY (IDFORM, IDCOMPT)
);


/* Index : ETREDOTE_FK                                        */

CREATE INDEX ETREDOTE_FK ON ETREDOTE (
   IDFORM ASC
);

/* Index : ETREDOTE2_FK                                       */

CREATE INDEX ETREDOTE2_FK ON ETREDOTE (
   IDCOMPT ASC
);
/* Modifications des tables */
ALTER TABLE ASSISTER ADD CONSTRAINT FK_ASSISTER_ASSISTER_PARTICIP FOREIGN KEY (NUMERO) REFERENCES PARTICIPANT (NUMERO);

ALTER TABLE ASSISTER ADD CONSTRAINT FK_ASSISTER_ASSISTER2_CONFEREN FOREIGN KEY (IDCONF) REFERENCES CONFERENCE (IDCONF);

ALTER TABLE BULLETIN ADD CONSTRAINT FK_BULLETIN_SUBVENTIO_FORMATEU FOREIGN KEY (IDFORM) REFERENCES FORMATEUR (IDFORM);

ALTER TABLE CONFERENCE ADD CONSTRAINT FK_CONFEREN_ANIMER_FORMATEU FOREIGN KEY (IDFORM) REFERENCES FORMATEUR (IDFORM);

ALTER TABLE COURS ADD CONSTRAINT FK_COURS_ENSEIGNER_FORMATEU FOREIGN KEY (IDFORM) REFERENCES FORMATEUR (IDFORM);

ALTER TABLE ENGAGER ADD CONSTRAINT FK_ENGAGER_ENGAGER_PARTICIP FOREIGN KEY (NUMERO) REFERENCES PARTICIPANT (NUMERO);

ALTER TABLE ENGAGER ADD CONSTRAINT FK_ENGAGER_ENGAGER2_COURS FOREIGN KEY (ANNEECOURS, CODECOURS) REFERENCES COURS (ANNEECOURS, CODECOURS);

ALTER TABLE FINANCER ADD CONSTRAINT FK_FINANCER_FINANCER_CONFEREN FOREIGN KEY (IDCONF) REFERENCES CONFERENCE (IDCONF);

ALTER TABLE FINANCER ADD CONSTRAINT FK_FINANCER_FINANCER2_BULLETIN FOREIGN KEY (DATEFIN) REFERENCES BULLETIN (DATEBUL);

ALTER TABLE PARTICIPER ADD CONSTRAINT FK_PARTICIP_PARTICIPE_PARTICIP FOREIGN KEY (NUMEROPART) REFERENCES PARTICIPANT (NUMERO);

ALTER TABLE PARTICIPER ADD CONSTRAINT FK_PARTICIP_PARTICIPE_SEQUENCE FOREIGN KEY (IDSQ) REFERENCES SEQUENCE (IDSQ);

ALTER TABLE PAYER ADD CONSTRAINT FK_PAYER_PAYER_SEQUENCE FOREIGN KEY (IDSQ) REFERENCES SEQUENCE (IDSQ);

ALTER TABLE PAYER ADD CONSTRAINT FK_PAYER_PAYER2_BULLETIN FOREIGN KEY (DATEPAY) REFERENCES BULLETIN (DATEBUL);

ALTER TABLE SEQUENCE ADD CONSTRAINT FK_SEQUENCE_CONTENIR_COURS FOREIGN KEY (ANNEECOURS, CODECOURS) REFERENCES COURS (ANNEECOURS, CODECOURS);

ALTER TABLE ETREDOTE ADD CONSTRAINT FK_ETREDOTE_ETREDOTE_FORMATEUR FOREIGN KEY (IDFORM) REFERENCES FORMATEUR (IDFORM);

ALTER TABLE ETREDOTE ADD CONSTRAINT FK_ETREDOTE_ETREDOTE2_COMPETENCE FOREIGN KEY (IDCOMPT) REFERENCES COMPETENCE (IDCOMPT);