--1. R1.
SELECT
    COUNT(*)
FROM
    COURS;

--2. R2.
SELECT
    COUNT(*)
FROM
    COURS
WHERE
    ANNEECOURS = 2023;

--3. R3.
SELECT
    C.DOMAINECONF,
    P.NOMPATIENT
FROM
    PARTICIPANT P
    INNER JOIN ASSISTER A
    ON A.NUMERO = P.NUMERO
    INNER JOIN CONFERENCE C
    ON A.IDCONF = C.IDCONF
WHERE
    C.DATECONF = '15-MAY-2024';

--4 R4.
SELECT
    P.NOMPATIENT
FROM
    PARTICIPANT P
    INNER JOIN ENGAGER E
    ON P.NUMERO = E.NUMERO
    INNER JOIN COURS C
    ON C.CODECOURS = E.CODECOURS
WHERE
    E.SOLDE < 0
    AND C.INTITULECOURS = 'Chirurgie cardiaque';

--5 R5.
SELECT
    CODEPOSTALPAT,
    COUNT(*)      AS NOMBRE_PART
FROM
    PARTICIPANT
GROUP BY
    CODEPOSTALPAT
ORDER BY
    NOMBRE_PART DESC FETCH FIRST 3 ROWS ONLY;

--6 R6.
SELECT
    C.IDCONF,
    C.DOMAINECONF,
    C.DATECONF
FROM
    CONFERENCE C
    JOIN ASSISTER A
    ON C.IDCONF = A.IDCONF
GROUP BY
    C.IDCONF,
    C.DOMAINECONF,
    C.DATECONF
ORDER BY
    COUNT(A.NUMERO) DESC FETCH FIRST ROW ONLY;

--7 R7.
SELECT
    F.IDFORM,
    F.PRENOMFORM,
    F.TITREFORM,
    COUNT(E.NUMERO) AS TOTALPARTICIPANTS
FROM
    FORMATEUR F
    JOIN COURS C
    ON F.IDFORM = C.IDFORM
    JOIN ENGAGER E
    ON C.ANNEECOURS = E.ANNEECOURS
    AND C.CODECOURS = E.CODECOURS
GROUP BY
    F.IDFORM,
    F.PRENOMFORM,
    F.TITREFORM
ORDER BY
    COUNT(E.NUMERO) DESC FETCH FIRST ROW ONLY;

--8 R8.
SELECT
    P.NUMERO,
    P.NOMPATIENT,
    P.ADRESSEPAT,
    SUM(E.SOLDE) AS TOTALOWED
FROM
    PARTICIPANT P
    JOIN ENGAGER E
    ON P.NUMERO = E.NUMERO
WHERE
    E.SOLDE > 0
GROUP BY
    P.NUMERO,
    P.NOMPATIENT,
    P.ADRESSEPAT
ORDER BY
    SUM(E.SOLDE) DESC;