--1. R1.
SELECT
    SUM(C.CODECOURS)
FROM
    COURS C;

--2. R2.
SELECT
    C.INTITULECOURS
FROM
    COURS C
WHERE
    (C.ANNEECOURS >= '01-JAN-2023'
    AND C.ANNEECOURS < '01-JAN-2024');

--3. R3.
SELECT
    C.DOMAINECONF,
    P.NOMPATIENT
FROM
    PARTICIPANT P
    INNER JOIN ASSISTER A
    ON A.NUMERO = P.NUMERO
    INNER JOIN CONFERENCE C
    ON A.IDCONF = C.IDCONF
WHERE
    C.DATECONF = '15-OCT-2023';

--4 R4.
SELECT
    P.NOMPATIENT
FROM
    PARTICIPANT P
    INNER JOIN ENGAGER E
    ON P.NUMERO = E.NUMERO
WHERE
    E.SOLDE < 0;

--5 R5.
SELECT
    CODEPOSTALPAT,
    COUNT(*) AS NOMBRE_PART
FROM
    PARTICIPANT
GROUP BY
    POSTAL_CODE
ORDER BY
    PARTICIPANT_COUNT DESC FETCH FIRST 3 ROWS ONLY;

--6 R6.
SELECT
    C.IDCONF,
    C.DOMAINECONF,
    C.DATECONF
FROM
    CONFERENCE C
    JOIN ASSISTER A
    ON C.IDCONF = A.IDCONF
GROUP BY
    C.IDCONF,
    C.DOMAINECONF,
    C.DATECONF
ORDER BY
    COUNT(A.NUMERO) DESC FETCH FIRST ROW ONLY;

--7 R7.
SELECT
    F.IDFORM,
    F.PRENOMFORM,
    F.TITREFORM,
    COUNT(E.NUMERO) AS TOTALPARTICIPANTS
FROM
    FORMATEUR F
    JOIN COURS C
    ON F.IDFORM = C.IDFORM
    JOIN ENGAGER E
    ON C.ANNEECOURS = E.ANNEECOURS
    AND C.CODECOURS = E.CODECOURS
GROUP BY
    F.IDFORM,
    F.PRENOMFORM,
    F.TITREFORM
ORDER BY
    COUNT(E.NUMERO) DESC FETCH FIRST ROW ONLY;

--8 R8.
SELECT
    P.NUMERO,
    P.NOMPATIENT,
    P.ADRESSEPAT,
    SUM(E.SOLDE) AS TOTALOWED
FROM
    PARTICIPANT P
    JOIN ENGAGER E
    ON P.NUMERO = E.NUMERO
WHERE
    E.SOLDE > 0
GROUP BY
    P.NUMERO,
    P.NOMPATIENT,
    P.ADRESSEPAT
ORDER BY
    SUM(E.SOLDE) DESC;